export const postsData = [
  {
    name: "Strawberry Shortcake Hat",
    description: "A cute crochet hat I made for myself.",
    rating: 5,
    user: "CrochetQueen",
    photoName: "crochet-projects/strawberry.png",
    status: "completed",
    steps: [
      {
        photoName: "crochet-projects/strawberry1.png",
        description: "Crochet a flat circle base.",
      },
      {
        photoName: "crochet-projects/strawberry2.png",
        description: "Build wavy hat walls.",
      },
      {
        photoName: "crochet-projects/strawberry3.png",
        description: "Stitch a basic leaf.",
      },
      {
        photoName: "crochet-projects/strawberry4.png",
        description: "Attach leaves around the top.",
      },
      {
        photoName: "crochet-projects/strawberry5.png",
        description: "Behold your berry cute hat!",
      },
      {
        photoName: "crochet-projects/strawberry6.png",
        description: "Rock it and share the sweetness!",
      },
    ],
    categories: ["hat", "clothing", "fruit", "crochet"],
    isFavorited: false,
  },
  {
    name: "Octopus",
    description: "A cute crochet octopus I made for my family.",
    rating: 5,
    user: "CrochetQueen",
    photoName: "crochet-projects/octo.png",
    status: "completed",
    steps: [],
    categories: ["toy", "animal", "crochet"],
    isFavorited: false,
  },
  {
    name: "Coasters",
    description: "Cute crochet coasters I made for me and my partner.",
    rating: null,
    user: "CrochetQueen",
    photoName: "crochet-projects/coasters.png",
    status: "completed",
    steps: [],
    categories: ["coaster", "home", "crochet"],
    isFavorited: false,
  },
  {
    name: "Leg Warmers",
    description: "Leg warmers I'm making for my trip to Chicago.",
    rating: null,
    user: "CrochetQueen",
    photoName: null,
    status: "in-progress",
    steps: [],
    categories: ["clothing", "crochet"],
    isFavorited: false,
  },
  {
    name: "Strawberry Seatbelt Cover",
    description: "A cute crochet seatbelt cover my friend's car.",
    rating: 3,
    user: "CrochetQueen",
    photoName: "crochet-projects/seatbeltcover.png",
    status: "completed",
    steps: [],
    categories: ["car", "fruit", "crochet"],
    isFavorited: false,
  },
  {
    name: "Luffy Hat",
    description: "A cute crochet hat I made for my partner.",
    rating: 5,
    user: "CrochetQueen",
    photoName: "crochet-projects/luffyhat.png",
    status: "completed",
    steps: [],
    categories: ["cute", "hat", "crochet"],
    isFavorited: false,
  },
  {
    name: "Hearts",
    description: "First every thing i made",
    rating: 5,
    user: "CrochetQueen",
    photoName: "crochet-projects/smallhearts.png",
    status: "completed",
    steps: [],
    categories: ["cute", "nostalgic", "crochet"],
    isFavorited: false,
  },
];

export default postsData;
